
-- Count of all customers
SELECT COUNT(*) FROM customer_churn;


-- Average Monthly Charges
SELECT ROUND(AVG(monthly_charge), 1) AS avg_monthly_charge
FROM customer_churn;


-- Rounding Tenure in months to years
SELECT CEILING(tenure_in_months / 12) AS tenure_in_years
FROM customer_churn;


-- Total Number of Churned Customers
SELECT COUNT(customer_status) AS churn_count
FROM customer_churn
WHERE customer_status = 'Churned';


-- Total Number of Gender with the highest churn count
SELECT customer_status, MAX(gender) AS gender, COUNT(customer_status) AS churn_count
FROM customer_churn
WHERE customer_status = 'Churned'
GROUP BY customer_status, gender;


-- Total Revenue Generated by the Company Across Customer Status
SELECT customer_status, ROUND(SUM(total_revenue), 0) AS total_revenue
FROM customer_churn
GROUP BY customer_status;


-- Churn Rate of Customers
WITH churn AS (
SELECT COUNT(*) AS churn_count
FROM customer_churn
WHERE customer_status = 'Churned'
), total AS (
SELECT COUNT(DISTINCT customer_id) AS total_count
FROM customer_churn
)
SELECT ROUND((CAST(churn_count AS NUMERIC) / total_count) * 100, 2) AS churn_rate
FROM churn
CROSS JOIN total;


-- Churn Rate Across type of Contract
WITH contract_cte AS (
SELECT contract, customer_status, COUNT(*) AS churn_count
FROM customer_churn
WHERE customer_status = 'Churned'
GROUP BY contract, customer_status
), total AS (
SELECT COUNT(DISTINCT customer_id) AS total_count
FROM customer_churn
)
SELECT contract, CEILING((CAST(churn_count AS NUMERIC) / total_count) * 100) AS churn_rate
FROM contract_cte
CROSS JOIN total
GROUP BY contract, churn_count, total_count;


-- Churn Rate Across Customers Payment Method
WITH payment_cte AS (
SELECT payment_method, customer_status, COUNT(*) AS churn_count
FROM customer_churn
WHERE customer_status = 'Churned'
GROUP BY payment_method, customer_status
), total AS (
SELECT COUNT(DISTINCT customer_id) AS total_count
FROM customer_churn
)
SELECT payment_method, (CAST(churn_count AS NUMERIC) / total_count) * 100 AS churn_rate
FROM payment_cte
CROSS JOIN total
GROUP BY payment_method, churn_count, total_count;